# Generated by Django 4.1.3 on 2022-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='username'),
        ),
    ]
