# Generated by Django 4.1.3 on 2022-11-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='username',
        ),
    ]
