# Generated by Django 4.1.3 on 2022-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
